name: app_gestor_financiero
description: Gestor de gastos personales con Flutter, Clean Architecture, Riverpod y Drift
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  fl_chart: ^0.66.0
  flutter_slidable: ^3.0.1
  sticky_headers: ^0.2.0
  share_plus: ^10.1.2
  intl: ^0.19.0
  dropdown_button2: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true

